# Generated by Django 4.1.4 on 2022-12-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0006_item_otd_order_orderitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quanitity',
            new_name='quantity',
        ),
    ]
